name: Mirror to GitLab

on:
  push:
    branches:
      - main   # ggf. anpassen (master?)

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/s.dierks/lemurcalls.git
          git push --mirror gitlab